general:
  rows: 12
  cols: 20
  start_location: [6, 6]
  total_steps: 100

items:
  Apple:
    blocks: false
    collects: true
    unique: false
    locations:
      [1,1]: 3
      [10,2]: 5
      [18,11]: 2
    visual:
      color: "#ff0000"

  Banana:
    blocks: false
    collects: true
    unique: false
    locations:
      [2,8]: 4
      [15,5]: 3
    visual:
      color: "#ffff00"

  Orange:
    blocks: false
    collects: true
    unique: false
    locations:
      [4,10]: 3
      [7,3]: 2
      [19,0]: 1
    visual:
      color: "#ffa500"

  Boulder:
    blocks: true
    collects: false
    unique: true
    locations:
      [5,5]: 1
      [6,5]: 1
      [7,5]: 1
      [5,6]: 1
      [6,6]: 1
      [7,6]: 1
      [8,5]: 1
      [9,5]: 1
    visual:
      color: "#808080"

  Poison:
    blocks: false
    collects: false
    unique: false
    locations:
      [3,3]: 1
      [12,7]: 1
      [16,9]: 1
      [2,11]: 1
      [18,2]: 1
    visual:
      color: "#00aa00"

  Key:
    blocks: false
    collects: true
    unique: true
    locations:
      [0,11]: 1
    visual:
      color: "#ff00ff"

  Portal:
    blocks: false
    collects: false
    unique: true
    locations:
      [19,11]: 1
    visual:
      color: "#00ffff"

end_condition:
  and:
    # 1) You must pick up at least 8 apples
    - greater_than:
        property: player.inventory.Apple
        value: 8

    # 2) Exactly 4 bananas
    - equals:
        property: player.inventory.Banana
        value: 4

    # 3) Avoid all poison (never step on any Poison tile)
    - for_all:
        over: player.visit_tile.Poison
        equals: false

    # 4) Reach the Portal at least once
    - for_any:
        over: player.visit_tile.Portal
        equals: true

    # 5) And you must not run out of steps
    - greater_than:
        property: player.steps_remaining
        value: 0
