general:
  rows: 5
  cols: 10
  start_location: [0, 0]
  total_steps: 0  # unlimited

items:
  Apple:
    blocks: false
    collects: true
    unique: false
    locations:
      [1, 2]: 1
      [9, 0]: 1
    visual:
      color: "#ff0000"

  Banana:
    blocks: false
    collects: true
    unique: false
    locations:
      [5, 3]: 3
    visual:
      color: "#ffff00"

  Orange:
    blocks: false
    collects: true
    unique: false
    locations:
      [8, 4]: 1
    visual:
      color: "#ffa500"

end_condition:
  and:
    - equals:
        property: player.inventory.Apple
        value: 2
    - equals:
        property: player.inventory.Banana
        value: 3
    - equals:
        property: player.inventory.Orange
        value: 1
