general:
  rows: 5
  cols: 5
  start_location: [0, 0]
  max_steps: 50

items:
  key:
    blocks: false
    collects: true
    unique: true
    locations:
      "[1,1]": 1
    visual:
      color: red

end_condition:
  equals:
    property: player.score
    value: 1
